### ISSUE TITLE
Use with whereHas

### ISSUE THREAD

**Issue by canfiax** [znck/belongs-to-through#13]
I could be cool if you could use the `belongsToThrough` in methods such as `whereHas`, `has`, etc.

Currently I have tested with whereHas and it fails with the error:

	BadMethodCallException thrown with message "Call to undefined method Illuminate\Database\Query\Builder::getHasCompareKey()"

	Stacktrace:
	#128 BadMethodCallException in /home/vagrant/Projects/myapp/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2251
	#127 Illuminate\Database\Query\Builder:__call in /home/vagrant/Projects/myapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1340
	#126 call_user_func_array in /home/vagrant/Projects/myapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1340
	#125 Illuminate\Database\Eloquent\Builder:__call in /home/vagrant/Projects/myapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php:344
	#124 call_user_func_array in /home/vagrant/Projects/myapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php:344
	#123 Illuminate\Database\Eloquent\Relations\Relation:__call in /home/vagrant/Projects/myapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php:165
	#122 Illuminate\Database\Eloquent\Relations\Relation:getRelationQuery in /home/vagrant/Projects/myapp/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:776
	#121 Illuminate\Database\Eloquent\Builder:has in /home/vagrant/Projects/myapp/app/UserSubscription.php:43

**Comment by znck** [comment]
It has a test case for that. But failing.
Eloquent might be having some breaking changes.

BTW on it, will be fixed in a couple of days.

**Comment by dannyweeks** [comment]
Hey @znck

I have had a little root through this and at first glance it looks like the relation class `BelongsToThrough` needs a `getHasCompareKey` method. Similar to [HasManyThrough](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Relations/HasManyThrough.php#L392). 

I added the below method but the `test_has_relation` test is giving me 3 results not the expected 16.

```php
/**
     * Get the key for comparing against the parent key in "has" query.
     *
     * @return string
     */
    public function getHasCompareKey()
    {
        return $this->getRelated()->getQualifiedKeyName();
    }
```

Happy to lend a hand if I can!

Danny

**Comment by znck** [comment]
A recursive join query is required for `has` query.
