### ISSUE TITLE
Belongs to through many to many pivote

### ISSUE THREAD

**Issue by sn0opr** [znck/belongs-to-through#19]
Is it possible to get to relation that is through a many to many relation ?

**Comment by znck** [comment]
Provide an example.

**Comment by sn0opr** [comment]
for example:
a Teacher teaches many Subjects (belongsToMany)
a Subject belongsTo SchoolLevel

I want to get the SchoolLevels for a given Teacher through the Subject relationship which is a ManyToMany relation.

**Comment by znck** [comment]
```sql
select school_levels.* from school_levels left join teachers on teachers.id = subjects.teacher_id left join subjects on subjects.id = school_levels.subject_id where teachers.id = ?
```

The relation translates to this query. If your tables have required fields then you can.
