### ISSUE TITLE
How can I change the name of the keys?

### ISSUE THREAD

**Issue by andreshg112** [znck/belongs-to-through#21]
I need to do something like this:
```
public function sede() {
        return $this->belongsToThrough(Sede::class, Vendedor::class, [], 'vendedor_id');
    }
```
But when I do it, I got this:

`QueryException in Connection.php line 729: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pedidos.vendedor_idvendedore_id' in 'on clause' (SQL: select `sedes`.*, `pedidos`.`id` as `__deep_related_through_key` from `sedes` left join `vendedores` on `sedes`.`id` = `vendedores`.`sede_id` left join `pedidos` on `vendedores`.`id` = `pedidos`.`vendedor_idvendedore_id` where `pedidos`.`id` in (2997, 2998) and `sedes`.`deleted_at` is null)`

When I do it without the key and array:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pedidos.vendedore_id' in 'on clause' (SQL: select `sedes`.*, `pedidos`.`id` as `__deep_related_through_key` from `sedes` left join `vendedores` on `sedes`.`id` = `vendedores`.`sede_id` left join `pedidos` on `vendedores`.`id` = `pedidos`.`vendedore_id` where `pedidos`.`id` in (2997, 2998) and `sedes`.`deleted_at` is null)`

I have a problem with it because you're using Str::singular. This is just for english words. How can I change the name of my foreign key?
Note: The plural for 'vendedor' is 'vendedores', in spanish.

**Comment by znck** [comment]
``` php
 return $this->belongsToThrough(Sede::class, [ ['vendedor_id', Vendedor::class] ]);
```

**Comment by andreshg112** [comment]
Doing this:

`public function sede() {
        return $this->belongsToThrough(Sede::class, [ ['vendedor_id', Vendedor::class] ]);
    }`

I'm getting this:

`FatalErrorException in BelongsToThrough.php line 40: Class 'vendedor_id' not found

    in BelongsToThrough.php line 40

`

**Comment by znck** [comment]
Oh! My bad.

```
return $this->belongsToThrough(Sede::class, [ [Vendedor::class, 'vendedor_id'] ]);
```

There is an [example in tests](https://github.com/znck/belongs-to-through/blob/master/tests/BelongsToThroughTest.php#L144). I guess this needs to be documented.
