### ISSUE TITLE
BadMethodCallException

### ISSUE THREAD

**Issue by hippieua** [znck/belongs-to-through#3]
Laravel 5.0@homestead

    <?php namespace App;

    use Illuminate\Database\Eloquent\Model;
    use \Znck\Eloquent\Relations\BelongsToThroughTrait;

        class Championship extends Model {

        public function masterChampionship()
        {
            return $this->belongsTo('App\MasterChampionship');
        }

        public function country()
        {
            return $this->belongsToThrough('App\Country', 'App\MasterChampionship');
        }
    }

artisan ticker:

    App\Championship::first()->masterChampionship->country

gives correct result

    App\Championship::first()->country

Gives 
    BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::belongsToThrough()'

**Comment by znck** [comment]
@hippieua You have to add trait to the class.
```php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
class Championship extends Model {
    use \Znck\Eloquent\Relations\BelongsToThroughTrait; // Put it here

    public function masterChampionship()
    {
        return $this->belongsTo('App\MasterChampionship');
    }

    public function country()
    {
        return $this->belongsToThrough('App\Country', 'App\MasterChampionship');
    }
}
```

**Comment by hippieua** [comment]
Got it. Thank you!
