### ISSUE TITLE
[Proposition] Belongs To Through multiple models

### ISSUE THREAD

**Issue by sn0opr** [znck/belongs-to-through#4]
What if we need to acces to a related model through multiple models (a recursive thing)

**Comment by znck** [comment]
@sn0opr Can you suggest any example?

**Comment by sn0opr** [comment]
@znck 
First of all I would like to thank you about this implementation, I've been searching for it for a long time.
The idea is to access to a more deeper (or unlimited deep) related model **Example:**
*Person* belongs to a *City*
*City* belongs to a *Country*
*Country* belongs to *Continent*

With the current **BelongsToThrough** method we can only access to the Country of a Person, but we can't get the Continent of a Person.
So I suggest to do something like this

```
//Person Model class
public function continent()
{
    return $this->belongsToThrough(Continent::class, [City::class, Country::class]);
}
```
The second parameter is an array that contains the path to get to the needed relation, it can be more than two...
